version: "3.8"

services:
  resource-management-bc:
    image: resource-management-bc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/resource-management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=resource-management
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
